[profile.default]
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
libraries = []
optimizer = true
verbosity = 0
solc = "0.8.21"
# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
